name: PlayerHead  
main: Legoboy\PlayerHead\Main
version: "2.0.0-beta"
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: Legoboy
commands:
  head:
    usage: "/head (sell)"
    description: "PlayerHead Main Command!!!"
    permission: head.sell
